Theory and Practice of FEM -- a parametrized Poisson Solver: Poisson< dim > Class Template Reference
Poisson< dim > Class Template Reference
#include <poisson.h>
Public Types
using CopyData = MeshWorker::CopyData<1, 1, 1>
using ScratchData = MeshWorker::ScratchData<dim>
Public Member Functions
Poisson ()
void print_system_info ()
void run ()
void initialize (const std::string &filename)
void parse_string (const std::string &par)
Protected Member Functions
void assemble_system_one_cell (const typename DoFHandler< dim >::active_cell_iterator &cell, ScratchData &scratch, CopyData &copy)
void copy_one_cell (const CopyData &copy)
void make_grid ()
void refine_grid ()
void setup_system ()
void assemble_system ()
void assemble_system_on_range (const typename DoFHandler< dim >::active_cell_iterator &begin, const typename DoFHandler< dim >::active_cell_iterator &end)
void solve ()
void estimate ()
void mark ()
void output_results (const unsigned cycle) const
Protected Attributes
MPI_Comm mpi_communicator
ConditionalOStream pcout
TimerOutput timer
parallel::distributed::Triangulation< dim > triangulation
std::unique_ptr< FE_Q< dim > > fe
std::unique_ptr< MappingQGeneric< dim > > mapping
DoFHandler< dim > dof_handler
AffineConstraints< double > constraints
IndexSet locally_owned_dofs
IndexSet locally_relevant_dofs
LA::MPI::SparseMatrix system_matrix
LA::MPI::Vector locally_relevant_solution
LA::MPI::Vector solution
LA::MPI::Vector system_rhs
Vector< float > error_per_cell
std::string estimator_type = "exact"
std::string marking_strategy = "global"
std::pair< double, double > coarsening_and_refinement_factors = {0.03, 0.3}
FunctionParser< dim > forcing_term
FunctionParser< dim > coefficient
FunctionParser< dim > exact_solution
FunctionParser< dim > dirichlet_boundary_condition
FunctionParser< dim > neumann_boundary_condition
FunctionParser< dim > pre_refinement
unsigned int fe_degree = 1
unsigned int mapping_degree = 1
unsigned int n_refinements = 4
unsigned int n_refinement_cycles = 1
std::string output_filename = "poisson"
int number_of_threads = -1
std::set< types::boundary_id > dirichlet_ids = {0}
std::set< types::boundary_id > neumann_ids
std::string forcing_term_expression = "1"
std::string coefficient_expression = "1"
std::string exact_solution_expression = "0"
std::string dirichlet_boundary_conditions_expression = "0"
std::string neumann_boundary_conditions_expression = "0"
std::string pre_refinement_expression = "0"
std::map< std::string, double > constants
std::string grid_generator_function = "hyper_cube"
std::string grid_generator_arguments = "0: 1: false"
ParsedConvergenceTable error_table
bool use_direct_solver = true
ParameterAcceptorProxy< ReductionControl > solver_control
Friends
template<typename Integral >
class PoissonTester
Additional Inherited Members
Private Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
unsigned int get_acceptor_id () const
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Member Functions inherited from Subscriptor
Subscriptor ()
Subscriptor (const Subscriptor &)
Subscriptor (Subscriptor &&) noexcept
virtual ~Subscriptor ()
Subscriptor & operator= (const Subscriptor &)
Subscriptor & operator= (Subscriptor &&) noexcept
void serialize (Archive &ar, const unsigned int version)
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
void subscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
void unsubscribe (std::atomic< bool > *const validity, const std::string &identifier="") const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Static Private Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Private Member Functions inherited from Subscriptor
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Private Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
const std::string section_name
std::vector< std::string > subsections
Static Private Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Detailed Description
template<int dim>
class Poisson< dim >
Solve the Poisson problem, with Dirichlet or Neumann boundary conditions, on all geometries that can be generated by the functions in the GridGenerator namespace.
Definition at line 92 of file poisson.h.
Member Typedef Documentation
CopyData
template<int dim> using Poisson< dim >::CopyData = MeshWorker::CopyData<1, 1, 1>
Definition at line 113 of file poisson.h.
ScratchData
template<int dim> using Poisson< dim >::ScratchData = MeshWorker::ScratchData<dim>
Definition at line 114 of file poisson.h.
Constructor & Destructor Documentation
Poisson()
template<int dim> Poisson< dim >::Poisson ()
Constructor. Initialize all parameters, and make sure the class is ready to run.
Definition at line 40 of file poisson.cc.
References ParameterAcceptor::add_parameter(), ParsedConvergenceTable::add_parameters(), Poisson< dim >::coarsening_and_refinement_factors, Poisson< dim >::coefficient_expression, Poisson< dim >::constants, Poisson< dim >::dirichlet_boundary_conditions_expression, Poisson< dim >::dirichlet_ids, e(), ParameterHandler::enter_subsection(), Poisson< dim >::error_table, Poisson< dim >::estimator_type, Poisson< dim >::exact_solution_expression, Poisson< dim >::fe_degree, Poisson< dim >::forcing_term_expression, Poisson< dim >::grid_generator_arguments, Poisson< dim >::grid_generator_function, ParameterHandler::leave_subsection(), Poisson< dim >::mapping_degree, Poisson< dim >::marking_strategy, Poisson< dim >::n_refinement_cycles, Poisson< dim >::n_refinements, Poisson< dim >::neumann_boundary_conditions_expression, Poisson< dim >::neumann_ids, Poisson< dim >::number_of_threads, Poisson< dim >::output_filename, Poisson< dim >::pre_refinement_expression, ParameterAcceptor::prm, this_mpi_process(), Poisson< dim >::timer, triangulation, and Poisson< dim >::use_direct_solver.
Member Function Documentation
assemble_system()
template<int dim> void Poisson< dim >::assemble_system () protected
Definition at line 322 of file poisson.cc.
References VectorOperation::add, copy(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
assemble_system_on_range()
template<int dim> void Poisson< dim >::assemble_system_on_range (const typename DoFHandler< dim >::active_cell_iterator & begin, const typename DoFHandler< dim >::active_cell_iterator & end) protected
Definition at line 289 of file poisson.cc.
References begin(), copy(), end(), update_gradients, update_JxW_values, update_quadrature_points, and update_values.
assemble_system_one_cell()
template<int dim> void Poisson< dim >::assemble_system_one_cell (const typename DoFHandler< dim >::active_cell_iterator & cell, ScratchData & scratch, CopyData & copy) protected
Definition at line 226 of file poisson.cc.
References cell_matrix(), copy(), MeshWorker::ScratchData< int dim, int spacedim >::reinit(), and FEValues< int dim, int spacedim >::shape_value().
copy_one_cell()
template<int dim> void Poisson< dim >::copy_one_cell (const CopyData & copy) protected
Definition at line 276 of file poisson.cc.
References copy().
estimate()
template<int dim> void Poisson< dim >::estimate () protected
Definition at line 380 of file poisson.cc.
References AssertThrow, cell_index, KellyErrorEstimator< int dim, int spacedim >::estimate(), FEValues< int dim, int spacedim >::get_function_laplacians(), VectorTools::H1_seminorm, VectorTools::integrate_difference(), FEValues< int dim, int spacedim >::JxW(), neumann, FEValues< int dim, int spacedim >::quadrature_point(), FEValues< int dim, int spacedim >::quadrature_point_indices(), FEValues< int dim, int spacedim >::reinit(), QGauss< int dim >::size(), std::sqrt(), update_hessians, update_JxW_values, and update_quadrature_points.
initialize()
template<int dim> void Poisson< dim >::initialize (const std::string & filename)
Definition at line 101 of file poisson.cc.
Referenced by main().
make_grid()
template<int dim> void Poisson< dim >::make_grid () protected
Definition at line 124 of file poisson.cc.
mark()
template<int dim> void Poisson< dim >::mark () protected
Definition at line 483 of file poisson.cc.
References Assert, parallel::distributed::GridRefinement::refine_and_coarsen_fixed_fraction(), parallel::distributed::GridRefinement::refine_and_coarsen_fixed_number(), and triangulation.
output_results()
template<int dim> void Poisson< dim >::output_results (const unsigned cycle) const protected
Definition at line 515 of file poisson.cc.
References DataOut< int dim, int spacedim >::add_data_vector(), DataOut< int dim, int spacedim >::attach_dof_handler(), DataOut< int dim, int spacedim >::build_patches(), std::max(), DataOut< int dim, int spacedim >::set_flags(), triangulation, DataOutBase::VtkFlags::write_higher_order_cells, GridOut::write_mesh_per_processor_as_vtu(), and DataOut< int dim, int spacedim >::write_vtu_in_parallel().
parse_string()
template<int dim> void Poisson< dim >::parse_string (const std::string & par)
Definition at line 113 of file poisson.cc.
References ParameterAcceptor::parse_all_parameters(), ParameterHandler::parse_input_from_string(), and ParameterAcceptor::prm.
print_system_info()
template<int dim> void Poisson< dim >::print_system_info ()
Definition at line 550 of file poisson.cc.
References MultithreadInfo::n_cores(), MultithreadInfo::n_threads(), and MultithreadInfo::set_thread_limit().
refine_grid()
template<int dim> void Poisson< dim >::refine_grid () protected
Definition at line 150 of file poisson.cc.
run()
template<int dim> void Poisson< dim >::run ()
Definition at line 565 of file poisson.cc.
Referenced by main().
setup_system()
template<int dim> void Poisson< dim >::setup_system () protected
Definition at line 161 of file poisson.cc.
References SparsityTools::distribute_sparsity_pattern(), DoFTools::extract_locally_relevant_dofs(), VectorTools::interpolate_boundary_values(), DoFTools::make_hanging_node_constraints(), DoFTools::make_sparsity_pattern(), and triangulation.
solve()
template<int dim> void Poisson< dim >::solve () protected
Definition at line 356 of file poisson.cc.
References SolverCG< typename VectorType >::solve().
Friends And Related Symbol Documentation
PoissonTester
template<int dim> template<typename Integral > friend class PoissonTester friend
Definition at line 216 of file poisson.h.
Member Data Documentation
coarsening_and_refinement_factors
template<int dim> std::pair<double, double> Poisson< dim >::coarsening_and_refinement_factors = {0.03, 0.3} protected
Definition at line 177 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
coefficient
template<int dim> FunctionParser<dim> Poisson< dim >::coefficient protected
Definition at line 181 of file poisson.h.
coefficient_expression
template<int dim> std::string Poisson< dim >::coefficient_expression = "1" protected
Definition at line 199 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
constants
template<int dim> std::map<std::string, double> Poisson< dim >::constants protected
Definition at line 204 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
constraints
template<int dim> AffineConstraints<double> Poisson< dim >::constraints protected
Definition at line 162 of file poisson.h.
dirichlet_boundary_condition
template<int dim> FunctionParser<dim> Poisson< dim >::dirichlet_boundary_condition protected
Definition at line 183 of file poisson.h.
dirichlet_boundary_conditions_expression
template<int dim> std::string Poisson< dim >::dirichlet_boundary_conditions_expression = "0" protected
Definition at line 201 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
dirichlet_ids
template<int dim> std::set<types::boundary_id> Poisson< dim >::dirichlet_ids = {0} protected
Definition at line 195 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
dof_handler
template<int dim> DoFHandler<dim> Poisson< dim >::dof_handler protected
Definition at line 161 of file poisson.h.
error_per_cell
template<int dim> Vector<float> Poisson< dim >::error_per_cell protected
Definition at line 174 of file poisson.h.
error_table
template<int dim> ParsedConvergenceTable Poisson< dim >::error_table protected
Definition at line 209 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
estimator_type
template<int dim> std::string Poisson< dim >::estimator_type = "exact" protected
Definition at line 175 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
exact_solution
template<int dim> FunctionParser<dim> Poisson< dim >::exact_solution protected
Definition at line 182 of file poisson.h.
exact_solution_expression
template<int dim> std::string Poisson< dim >::exact_solution_expression = "0" protected
Definition at line 200 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
fe
template<int dim> std::unique_ptr<FE_Q<dim> > Poisson< dim >::fe protected
Definition at line 159 of file poisson.h.
fe_degree
template<int dim> unsigned int Poisson< dim >::fe_degree = 1 protected
Definition at line 188 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
forcing_term
template<int dim> FunctionParser<dim> Poisson< dim >::forcing_term protected
Definition at line 180 of file poisson.h.
forcing_term_expression
template<int dim> std::string Poisson< dim >::forcing_term_expression = "1" protected
Definition at line 198 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
grid_generator_arguments
template<int dim> std::string Poisson< dim >::grid_generator_arguments = "0: 1: false" protected
Definition at line 207 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
grid_generator_function
template<int dim> std::string Poisson< dim >::grid_generator_function = "hyper_cube" protected
Definition at line 206 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
locally_owned_dofs
template<int dim> IndexSet Poisson< dim >::locally_owned_dofs protected
Definition at line 165 of file poisson.h.
locally_relevant_dofs
template<int dim> IndexSet Poisson< dim >::locally_relevant_dofs protected
Definition at line 166 of file poisson.h.
locally_relevant_solution
template<int dim> LA::MPI::Vector Poisson< dim >::locally_relevant_solution protected
Definition at line 169 of file poisson.h.
mapping
template<int dim> std::unique_ptr<MappingQGeneric<dim> > Poisson< dim >::mapping protected
Definition at line 160 of file poisson.h.
mapping_degree
template<int dim> unsigned int Poisson< dim >::mapping_degree = 1 protected
Definition at line 189 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
marking_strategy
template<int dim> std::string Poisson< dim >::marking_strategy = "global" protected
Definition at line 176 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
mpi_communicator
template<int dim> MPI_Comm Poisson< dim >::mpi_communicator protected
Definition at line 153 of file poisson.h.
n_refinement_cycles
template<int dim> unsigned int Poisson< dim >::n_refinement_cycles = 1 protected
Definition at line 191 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
n_refinements
template<int dim> unsigned int Poisson< dim >::n_refinements = 4 protected
Definition at line 190 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
neumann_boundary_condition
template<int dim> FunctionParser<dim> Poisson< dim >::neumann_boundary_condition protected
Definition at line 184 of file poisson.h.
neumann_boundary_conditions_expression
template<int dim> std::string Poisson< dim >::neumann_boundary_conditions_expression = "0" protected
Definition at line 202 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
neumann_ids
template<int dim> std::set<types::boundary_id> Poisson< dim >::neumann_ids protected
Definition at line 196 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
number_of_threads
template<int dim> int Poisson< dim >::number_of_threads = -1 protected
Definition at line 193 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
output_filename
template<int dim> std::string Poisson< dim >::output_filename = "poisson" protected
Definition at line 192 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
pcout
template<int dim> ConditionalOStream Poisson< dim >::pcout protected
Definition at line 155 of file poisson.h.
pre_refinement
template<int dim> FunctionParser<dim> Poisson< dim >::pre_refinement protected
Definition at line 185 of file poisson.h.
pre_refinement_expression
template<int dim> std::string Poisson< dim >::pre_refinement_expression = "0" protected
Definition at line 203 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
solution
template<int dim> LA::MPI::Vector Poisson< dim >::solution protected
Definition at line 170 of file poisson.h.
solver_control
template<int dim> ParameterAcceptorProxy<ReductionControl> Poisson< dim >::solver_control protected
Definition at line 213 of file poisson.h.
system_matrix
template<int dim> LA::MPI::SparseMatrix Poisson< dim >::system_matrix protected
Definition at line 168 of file poisson.h.
system_rhs
template<int dim> LA::MPI::Vector Poisson< dim >::system_rhs protected
Definition at line 171 of file poisson.h.
timer
template<int dim> TimerOutput Poisson< dim >::timer mutable protected
Definition at line 156 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
triangulation
template<int dim> parallel::distributed::Triangulation<dim> Poisson< dim >::triangulation protected
Definition at line 158 of file poisson.h.
use_direct_solver
template<int dim> bool Poisson< dim >::use_direct_solver = true protected
Definition at line 211 of file poisson.h.
Referenced by Poisson< dim >::Poisson().
The documentation for this class was generated from the following files:
/github/workspace/include/poisson.h
/github/workspace/source/poisson.cc