name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build
      id: build
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Build
        setup-command: ''
        command: .scripts/dr.sh "mkdir build; cd build; cmake -GNinja ..; ninja;"
        timeout: 10
    - name: Run ctest
      id: run-ctest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Run ctest
        setup-command: ''
        command: .scripts/dr.sh "cd build; ctest -N; ctest --output-on-failure;"
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BUILD_RESULTS: "${{steps.build.outputs.result}}"
        RUN-CTEST_RESULTS: "${{steps.run-ctest.outputs.result}}"
      with:
        runners: build,run-ctest
